config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  get 'dashboard/overview' => 'dashboard#overview'
  get 'dashboard/music' => 'dashboard#music'
  get 'dashboard/leaderboard' => 'dashboard#leaderboard'
  get 'dashboard/tools' => 'dashboard#tools'
  get 'dashboard/prospects' => 'dashboard#prospects'
  get 'dashboard/analytics' => 'dashboard#analytics'
  get 'dashboard/revenue' => 'dashboard#revenue'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource_or_scope)
    dashboard_overview_path
  end

  private

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :PayPal
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def overview
    #code
  end

  def music
    #code
  end

  def leaderboard
    #code
  end

  def tools
    #code
  end

  def prospects
    #code
  end

  def analytics
    #code
  end

  def revenue
    #code
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div id="page-content-dashboard">
  <div class="twelve column"><h4>General Statistics</h4></div>
  <div class="row">
    <div class="four columns">
      <div class="total-views-count">
        <p>300,000</p>
        <h6>Total Views</h6>
      </div>
    </div>
    <div class="four columns">
      <div class="total-subscribers-count">
        <p>24,000</p>
        <h6>Total Subscribers</h6>
      </div>
    </div>
    <div class="four columns">
      <div class="total-revenue-count">
        <p>$192.00</p>
        <h6>Total Revenue</h6>
      </div>
    </div>
  </div>

  <table class="u-full-width">
    <thead>
      <tr>
        <th>Recent Videos</th>
        <th>Total Views</th>
        <th>Total Comments</th>
        <th>Total Likes / Dislikes</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Dave Gamache</td>
        <td>26</td>
        <td>Male</td>
        <td>San Francisco</td>
      </tr>
      <tr>
        <td>Dwayne Johnson</td>
        <td>42</td>
        <td>Male</td>
        <td>Hayward</td>
      </tr>
    </tbody>
  </table>

</div>

app/views/dashboard/overview.html.erb
<div class="container">

  <div class="row">
    <div class="twelve column">
      <h4>General Statistics</h4>
    </div>
  </div>

  <div class="row">
    <div class="three columns">
      <div class="total-views-count">
        <p>300,000</p>
        <h6>Total Views</h6>
      </div>
    </div>
    <div class="three columns">
      <div class="total-subscribers-count">
      <p>24,000</p>
      <h6>Total Subscribers</h6>
      </div>
    </div>
    <div class="three columns">
      <div class="total-videos-count">
        <p>4,000</p>
        <h6>Total Views</h6>
      </div>
    </div>
    <div class="three columns">
      <div class="total-revenue-count">
        <p>$192.00</p>
        <h6>Total Revenue</h6>
      </div>
    </div>
  </div>

  <div class="row">
    <table class="u-full-width">
      <thead>
        <tr>
          <th>Recent Videos</th>
          <th>Total Views</th>
          <th>Total Comments</th>
          <th>Total Likes / Dislikes</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Dave Gamache</td>
          <td>26</td>
          <td>Male</td>
          <td>San Francisco</td>
        </tr>
        <tr>
          <td>Dwayne Johnson</td>
          <td>42</td>
          <td>Male</td>
          <td>Hayward</td>
        </tr>
      </tbody>
    </table>

  </div>

app/views/dashboard/revenue.html.erb
<div class="container">

  <div class="row">
    <div class="twelve column">
      <h4>Revenue Statistics</h4>
    </div>
  </div>

  <div class="row">
    <div class="tweleve columns">
      <div class="total-revenue-count">
        <p>$192.00</p>
        <h6>Total Revenue of</h6>
      </div>
    </div>
  </div>

  <div class="row">
    <table class="u-full-width">
      <thead>
        <tr>
          <th>Month</th>
          <th>Earning</th>
          <th>Paid</th>
          <th>Owed</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Mar 2015</td>
          <td>$0.00</td>
          <td>None</td>
          <td>None</td>
        </tr>
        <tr>
          <td>Feb 2015</td>
          <td>$0.00</td>
          <td>None</td>
          <td>None</td>
        </tr>
        <tr>
          <td>Jan 2015</td>
          <td>$0.00</td>
          <td>None</td>
          <td>None</td>
        </tr>
        <tr>
          <td>Dec 2014</td>
          <td>$0.00</td>
          <td>None</td>
          <td>None</td>
        </tr>
      </tbody>
    </table>
  </div>

</div>

app/views/layouts/_main_navigation.html.erb
<div id="main_navigation" role="navigation">
  <div class="logo"><a href="/">Animus</a></div>

        <%= link_to "About", "#", class: "main-link" %>
        <%= link_to "Benefits", '#', class: "main-link" %>
        <%= link_to "Contact", '#', class: "main-link" %>

    <% if user_signed_in? %>
      <%= link_to destroy_user_session_path, class: "main-sign-out", method: :delete do %>
        <i class="fa fa-sign-out"></i><br>
        Sign Out
      <% end %>
      <% else %>
        <%= link_to new_user_session_path, class: "main-link main-sign-out" do %>
        <i class="fa fa-sign-in"></i><br>
        Sign In
        <% end %>
    <% end %>
</div>

<div id="nav-trigger">
    <span>Menu</span>
</div>
<nav id="nav-mobile"></nav>

<script>
$(document).ready(function(){
  $("#nav-mobile").html($("#nav-main").html());
  $("#nav-trigger span").click(function(){
      if ($("nav#nav-mobile ul").hasClass("expanded")) {
          $("nav#nav-mobile ul.expanded").removeClass("expanded").slideUp(250);
          $(this).removeClass("open");
      } else {
          $("nav#nav-mobile ul").addClass("expanded").slideDown(250);
          $(this).addClass("open");
      }
  });
});
</script>

app/views/layouts/_sidebar.html.erb
<div id="sidebar_navigation" role="navigation">
  <%= image_tag("animus_logo.png",alt: "Animus Logo", class: "logo") %>

    <%= link_to dashboard_overview_path, class: "link" do %>
      <i class="fa fa-globe"></i><br>
      Overview <br>
    <% end %>
    <%= link_to dashboard_music_path, class: "link" do %>
      <i class="fa fa-music"></i><br>
      Music <br>
    <% end %>
    <%= link_to dashboard_leaderboard_path, class: "link" do %>
      <i class="fa fa-bars"></i><br>
      Leaderboard <br>
    <% end %>
    <%= link_to dashboard_tools_path, class: "link" do %>
      <i class="fa fa-wrench"></i><br>
      Tools <br>
    <% end %>
    <%= link_to dashboard_prospects_path, class: "link" do %>
      <i class="fa fa-users"></i><br>
      Prospects <br>
    <% end %>
    <%= link_to dashboard_analytics_path, class: "link" do %>
      <i class="fa fa-line-chart"></i><br>
      Analytics <br>
    <% end %>
    <%= link_to dashboard_revenue_path, class: "link revenue" do %>
      <i class="fa fa-usd"></i><br>
      Revenue <br>
    <% end %>

    <div class="settings">
      <% if user_signed_in? %>
        <%= link_to edit_user_registration_path, class: "link account" do %>
          <i class="fa fa-gears"></i>
          Account Settings
        <% end %>
        <%= link_to destroy_user_session_path, class: "link sign-out", method: :delete do %>
          <i class="fa fa-sign-out"></i><br>
          Sign Out
        <% end %>
        <% else %>
          <%= link_to new_user_session_path, class: "link sign-out" do %>
          <i class="fa fa-sign-in"></i><br>
          Sign In
          <% end %>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Animus</title>
  <script src="//use.typekit.net/fmj8nhe.js"></script>
  <script>try{Typekit.load();}catch(e){}</script>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript" src="https://apis.google.com/js/client.js?onload=onJSClientLoad"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/sidebar' %>

    <button id="menu" class="button-primary">Menu</button>

    <div id="flash">
      <% flash.each do |name, msg| %>
       <%= content_tag(:div, msg, class: "alert alert-info #{name}") %>
      <% end %>
    </div>

    <%= yield %>

<script type="text/javascript">
  $(document).ready(function(){
    setTimeout(function(){
      $('#flash').fadeOut();
    }, 1000);
  });

   $("#menu").click(function(e) {
       e.preventDefault();
       $("#sidebar_navigation").toggleClass("toggled");
   });
</script>

</body>
</html>